security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        public_api:
            pattern: ^/api/auth
            stateless: true
            security: false

        api:
           pattern: ^/api
           stateless: true
           provider: app_user_provider
           custom_authenticators:
               - App\Security\JWTAuthenticator

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                success_handler: App\Security\LoginSuccessHandler   # ðŸ‘ˆ OBLIGATOIRE

            logout:
                path: app_logout
                target: /login

    access_control:
    
        - { path: ^/api/medecins, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }

        # Protected API
        - { path: ^/api, roles: ROLE_USER }

        # MÃ©decin (doit Ãªtre connectÃ© + avoir rÃ´le)
       
        - { path: ^/medecin, roles: [ROLE_MEDECIN, ROLE_ADMIN] }

        # Patient
        - { path: ^/patient, roles: ROLE_PATIENT }
    # Admin
        - { path: ^/admin, roles: ROLE_ADMIN }
           # SecrÃ©taire
        - { path: ^/secretaire, roles: ROLE_SECRETAIRE }
        
        - { path: ^/specialites, roles: [ROLE_ADMIN, ROLE_MEDECIN] }
        - { path: ^/abonnements, roles: ROLE_ADMIN }
        - { path: ^/medecin, roles: ROLE_ADMIN }
